baseURL: "https://mugunth.dev/"
languageCode: "en-us"
title: "Mugunth Kumar"
theme: "liftoff"

params:
  theme:
    defaultTheme: "dark"
    disableThemeToggle: false
    
  profileMode:
    enabled: true
    title: "Mugunth Kumar"
    subtitle: "Engineering Manager & Principal Engineer"
    imageUrl: "/images/profile.jpg"
    buttons:
      - name: Resume
        url: "/resume.pdf"
      - name: Contact
        url: "mailto:mugunth@mfamily.club"

  # Professional Information
  author:
    name: "Mugunth Kumar"
    email: "mugunth@mfamily.club"
    location: "Melbourne, Australia"
    phone: "0429 924 820"
    linkedin: "https://linkedin.com/in/mugunthkumar"

  # Skills Section
  skills:
    enabled: true
    title: "Skills & Expertise"
    items:
      - "Engineering Leadership"
      - "Mobile Development (iOS/Android)"
      - "Team Building & Mentoring"
      - "Agile Project Management"
      - "System Architecture"
      - "Cloud Infrastructure (AWS/Azure)"

  # Experience Section
  experience:
    enabled: true
    title: "Professional Experience"

  # Publications Section
  publications:
    enabled: true
    title: "Publications"

  footer:
    enabled: true
    credit: false

menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 10
    - identifier: "experience"
      name: "Experience"
      url: "/experience"
      weight: 20
    - identifier: "resume"
      name: "Resume"
      url: "/resume"
      weight: 30
    - identifier: "contact"
      name: "Contact"
      url: "/contact"
      weight: 40