baseURL = "https://mugunth.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Mugunth Kumar (MK)"
theme = "congo"

[params]
  description = "Engineering Manager & Principal Engineer"

  [params.homepage]
    layout = "profile"
    showRecent = false

  [params.header]
    layout = "hybrid"
    showTitle = true

  [params.footer]
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = true

  [params.article]
    showDate = false
    showDateUpdated = false
    showAuthor = false
    showBreadcrumbs = false
    showDraftLabel = true
    showEdit = false
    showHeadingAnchors = true
    showPagination = false
    showReadingTime = false
    showTableOfContents = true
    showTaxonomies = false
    showWordCount = false

  [params.profile]
    description = """
    Engineering Manager & Principal Engineer with nearly 20 years of experience in
    full-stack software architecture, design, and development. Managed software engineering
    teams for over a decade, building and mentoring high-performance teams.
    """
    subtitle = "Engineering Manager & Principal Engineer"

  # Author information
  [params.author]
    name = "Mugunth Kumar"
    email = "contact@mfamily.club"
    location = "Melbourne, Australia"

[[menu.main]]
  name = "Resume"
  pageRef = "resume"
  weight = 30

[[menu.main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
