baseURL = "https://mk.sg/"
languageCode = "en-au"
title = "Mugunth Kumar (MK)"
theme = "liftoff"

[params.theme]
defaultTheme = "dark"
disableThemeToggle = false

[params.profileMode]
enabled = true
title = "Mugunth Kumar (MK)"
subtitle = "Engineering Manager & Principal Engineer"
imageUrl = "/images/profile.jpg"

[[params.profileMode.buttons]]
name = "Resume"
url = "/resume.pdf"

[[params.profileMode.buttons]]
name = "Contact"
url = "mailto:mugunth@mfamily.club"

[params.author]
name = "Mugunth Kumar"
email = "mugunth@mfamily.club"
location = "Melbourne, Australia"
phone = "0429 924 820"
linkedin = "https://linkedin.com/in/mugunthkumar"

[params.skills]
enabled = true
title = "Skills & Expertise"
items = [
    "Engineering Leadership",
    "Mobile Development (iOS/Android)",
    "Team Building & Mentoring",
    "Agile Project Management",
    "System Architecture",
    "Cloud Infrastructure (AWS/Azure)"
]

[params.experience]
enabled = true
title = "Professional Experience"

[params.publications]
enabled = true
title = "Publications"

[params.footer]
enabled = true
credit = false

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 10

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience"
weight = 20

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume"
weight = 30

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 40