baseURL = "https://mk.sg/"
languageCode = "en-au"
title = "Mugunth Kumar (MK)"
theme = "hugo-liftoff"

[params]
# Site Parameters
description = "Engineering Manager & Principal Engineer with 20 years of experience"
showPostNavLinks = true
showShareButtons = false
showCodeCopyButtons = true
displayFullLangName = true
enableSearch = true

# Author Parameters
[params.author]
name = "Mugunth Kumar"
email = "mugunth@mfamily.club"
location = "Melbourne, Australia"
phone = "0429 924 820"
linkedin = "https://linkedin.com/in/mugunthkumar"

# Main Menu Items
[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Experience"
url = "/experience"
weight = 2

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4

# Module Configuration
[module]
[[module.imports]]
path = "github.com/wjh18/hugo-liftoff"

# Resume Section Parameters
[params.resume]
enable = true
showPagination = false
showDate = false
showAuthor = false
showReadingTime = false
showTaxonomies = false
