baseURL = "https://mugunth.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Mugunth Kumar (MK)"

[[module.imports]]
  path = "github.com/jpanther/congo/v2"

[params]

  [params.homepage]
    layout = "profile"
    showRecent = false

  [params.header]
    layout = "profile"
    showTitle = true

  [params.footer]
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = true

  [params.article]
    showDate = false
    showDateUpdated = false
    showAuthor = false
    showBreadcrumbs = false
    showDraftLabel = true
    showEdit = false
    showHeadingAnchors = true
    showPagination = false
    showReadingTime = false
    showTableOfContents = true
    showTaxonomies = false
    showWordCount = false

  # Author information
  [params.author]
    name = "Mugunth Kumar (He/Him)"
    email = "contact-mk@mfamily.club"
    location = "Melbourne, Australia"
    image = "img/mk.jpg"
    headline = "Engineering Manager & Principal Engineer"
    links = [
      {Github = "https://github.com/MKSG-MugunthKumar"},
        {LinkedIn = "https://www.linkedin.com/in/mugunthkumar/"},
        {Email = "mailto:contact-mk@mfamily.club"},
    ]

[[menu.main]]
  name = "Resume"
  pageRef = "resume"
  weight = 30

[[menu.main]]
  name = "Publications"
  pageRef = "publications"
  weight = 40

[[menu.main]]
  name = "Github"
  pageRef = "oss"
  weight = 50

[[menu.main]]
  name = "Values"
  pageRef = "values"
  weight = 60

[[menu.main]]
  name = "Contact"
  pageRef = "contact"
  weight = 70

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
