name: Generate Resume PDF
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Puppeteer and HTML-PDF
        run: |
          npm install -g puppeteer
          npm install -g html-pdf

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Site
        run: hugo --minify

      - name: Generate PDF
        run: |
          npx puppeteer-pdf \
            ./public/resume/index.html \
            ./public/resume.pdf \
            --format A4 \
            --margin "20mm" \
            --printBackground

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: ./public/resume.pdf
